#normal: "/home/massi/Documents/Sentieon_scripts/TNscope/Blood_NGS"
tumor: "/home/rada/Documents/TNscope/fastqs"
fasta: "/home/rada/Documents/TNscope/references/AWS/GRCh37/genome.fa"
dbsnp: "/home/rada/Documents/TNscope/references/hg19_v0_Homo_sapiens_assembly19.dbsnp138.vcf"
known_Mills_indels: "/home/rada/Documents/TNscope/references/hg19_v0_1000G_omni2.5.b37.vcf"
known_1000G_indels: "/home/rada/Documents/TNscope/references/hg19_v0_1000G_phase1.snps.high_confidence.b37.vcf"
workdir: "/home/rada/Documents/TNscope/"
platform: "ILLUMINA"
R1_suffix: "_R1_001.fastq.gz"
R2_suffix: "_R2_001.fastq.gz"
params:
        sentieon_install: "/home/rada/Documents/sentieon-genomics-202010.02"
        sentieon_license: "/home/rada/Documents/Sentieon/licence/GMC_SOR_usb127.lic"
        tmp_dir: "/home/rada/Documents/TNscope/logs"
