normal: "/home/massi/Documents/Sentieon_scripts/TNscope/Blood_NGS"
tumor: "/home/massi/Documents/GMS/Sentieon_GMS560/fastq"
fasta: "/home/massi/Documents/AWS/GRCh37/genome.fa"
dbsnp: "/home/massi/Downloads/dbsnp_138.hg19.vcf"
known_Mills_indels: "/home/massi/Downloads/Mills_and_1000G_gold_standard.indels.hg19.vcf"
known_1000G_indels: "/home/massi/Downloads/1000G_phase1.indels.hg19.vcf"
workdir: "/home/massi/Documents/GMS/Sentieon_GMS560"
platform: "ILLUMINA"
R1_suffix: "_R1_001.fastq.gz"
R2_suffix: "_R2_001.fastq.gz"
params:
        sentieon_install: "/path/to/sentieon"
        sentieon_license: "/home/rada/Documents/Sentieon/licence/GMC_SOR_usb127.lic"

